@echo off

set IMPORT_WAITTIME=-waittime 300
set IMPORT_NOREFRESH=
set IMPORT_NOUPDATE=
set IMPORT_NOEXPORTODBC=
set IMPORT_NOEXPORTSF=
set IMPORT_INSERTATTEMPTS=
set IMPORT_ENABLE_ATTACHMENTS=
set IMPORT_INTERACTIVEMODE=

call "%IMPORTER_DIRECTORY%\..\importer.bat" 