@echo off

set IMPORT_WAITTIME=-waittime 120
set IMPORT_NOREFRESH=
set IMPORT_NOUPDATE=
set IMPORT_NOEXPORTODBC=-noexportodbc
set IMPORT_NOEXPORTSF=
set IMPORT_INSERTATTEMPTS=-insertattempts 1
set IMPORT_EMAILATTACHMENTS=
set IMPORT_INTERACTIVEMODE=
set IMPORT_DISPLAYALERTS=

call "%IMPORTER_DIRECTORY%\..\importer.bat" 